[package]
name = "kon"
version = "0.1.15"
rust-version = "1.74"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = "0.19.1"
gamedig = "0.4.1"
once_cell = "1.19.0"
poise = "0.6.1"
reqwest = { version = "0.11.24", features = ["json"] }
serde = "1.0.197"
serde_json = "1.0.114"
serenity = "0.12.1"
sysinfo = "0.30.6"
tokio = { version = "1.36.0", features = ["macros", "signal", "rt-multi-thread"] }
tokio-postgres = "0.7.10"
uptime_lib = "0.3.0"

[[bin]]
name = "kon"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
