services:
  app:
    container_name: kon-app
    #image: git.toast-server.net/nwerosama/kon:master
    build: .
    restart: unless-stopped
    env_file: .env.bot
  #   depends_on:
  #     - cache
  # cache:
  #   container_name: kon-redis
  #   image: redis/redis-stack-server:7.4.0-v1
  #   restart: unless-stopped
  #   ports:
  #     - 37935:6379/tcp
