version: '3.8'
services:
  bot:
    container_name: kon
    image: 'git.toast-server.net/toast/kon:main'
    build: .
    env_file:
      - .env
    restart: unless-stopped
  db:
    container_name: kon-database
    image: postgres:16.1-alpine3.19@sha256:b1413d8f37470f1fb355ea833d91855d6e24929e8f4336984c5be0de62947a25
    restart: unless-stopped
    ports:
      - 37930:5432/tcp
    volumes:
      - /var/lib/docker/volumes/kon-database:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
