version: '3.8'
services:
  bot:
    container_name: kon
    #image: 'git.toast-server.net/toast/kon:main'
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: kon-database
    image: postgres:16.2-alpine3.19@sha256:5af921f3ef049fd6df09f9a5d1b858f49e8dc32cdb399e1a5075eff6b6c956b7
    restart: unless-stopped
    ports:
      - 37930:5432/tcp
    volumes:
      - /var/lib/docker/volumes/kon-database:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
