name: Deploy to host
on:
  registry_package:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-22.04-node
    steps:
      - name: SSH into Docker Host
        uses: appleboy/ssh-action@2451745138b602d3e100a6def50c8e4e39591d4c # v1.0.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd kon && docker compose pull && \
            docker compose up -d --remove-orphans && docker image prune -f
