[package]
name = "kon_tokens"
version = "0.2.0"
edition = "2024"

[dependencies]
poise = { workspace = true }
tokenservice-client = { version = "0.4.5", registry = "gitea" }
tokio = { workspace = true }
